app/urls.py
from django.urls import path

from app.views import index_view


urlpatterns = [
    path('', index_view, name='index'),
]

dashboard/urls.py
from django.urls import path

from dashboard.views import dashboard_view, dashboard_admin_view

app_name= 'dashboard'

urlpatterns = [
    path('', dashboard_view, name='dashboard'),
    path('dashboard_admin_view/', dashboard_admin_view, name='dashboard_admin_view'),
]

dat/urls.py
from django.urls import path

from dat.views import (dat_add, dat_list, dat_update, dat_view, 
                       dat_destroy, export_dat_xls, export_dat_csv, Export_Dat_pdf)

app_name= 'dat'

urlpatterns = [
    path('dat-add/', dat_add, name='dat_add'),
    path('dat-list/', dat_list, name='dat_list'),
    path('dat-update/<int:id>/', dat_update, name='dat_update'),
    path('dat-view/<int:id>/', dat_view, name='dat_view'),
    path('dat-destroy/<int:id>/', dat_destroy, name='dat_destroy'),
    path('export/xls/', export_dat_xls, name='export_dat_xls'),
    path('export/csv/', export_dat_csv, name='export_dat_csv'),
    path('export/pdf/<int:id>/', Export_Dat_pdf.as_view(), name='export_dat_pdf'),
]

renouvellement/urls.py
from django.urls import path

from renouvellement.views import (
    renouvellement_add, renouvellement_list, 
    renouvellement_update, renouvellement_view, 
    renouvellement_destroy, export_renouvellement_xls, export_renouvellement_csv, Export_Renouvellement_pdf)

app_name = 'renouvellement'

urlpatterns = [
    path('renouvellement_add/', renouvellement_add, name='renouvellement_add'),
    path('renouvellement_list/', renouvellement_list, name='renouvellement_list'),
    path('renouvellement_update/<int:id>/', renouvellement_update, name='renouvellement_update'),
    path('renouvellement_view/<int:id>/', renouvellement_view, name='renouvellement_view'),
    path('renouvellement_destroy/<int:id>/', renouvellement_destroy, name='renouvellement_destroy'),
    path('export/xls/', export_renouvellement_xls, name='export_renouvellement_xls'),
    path('export/csv/', export_renouvellement_csv, name='export_renouvellement_csv'),
    path('export/pdf/<int:id>/', Export_Renouvellement_pdf.as_view(), name='export_renouvellement_pdf'),
]

scripting/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from scripting.search import GlobalSearchAPIView


handler400 = 'scripting.views_errors_page.handler400'
handler403 = 'scripting.views_errors_page.handler403'
handler404 = 'scripting.views_errors_page.handler404'
handler500 = 'scripting.views_errors_page.handler500'
handler503 = 'scripting.views_errors_page.handler503'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('api/', GlobalSearchAPIView.as_view()),
    path('app/', include('app.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('forms/', include('forms.urls')),
    path('pbx/', include('pbx.urls')),
    path('agenda/', include('agenda.urls')),
    path('dat/', include('dat.urls')),
    path('acquisition/', include('acquisition.urls')),
    path('commprom/', include('commprom.urls')),
    path('comptedormant/', include('comptedormant.urls')),
    path('recouvrement/', include('recouvrement.urls')),
    path('renouvellement/', include('renouvellement.urls')),
    path('contacts/', include('contacts.urls')),
    path('issabel/', include('issabel.urls')),
    path('param/', include('paramurl.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_ROOT,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
  

renouvellement/models.py
from django.db import models
from django.contrib.auth.models import User


from forms.statut import STATUTS
from contacts.models import Contact
# Create your models here.
class Renouvellement(models.Model):
    user             = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date     = models.DateTimeField(auto_now_add=True)
    Contact          = models.ForeignKey(Contact, on_delete=models.CASCADE)
    questions1       = models.CharField(max_length=200, null=True, blank=True, default='-')
    questions2       = models.CharField(max_length=200, null=True, blank=True, default='-')
    questions3       = models.CharField(max_length=200, null=True, blank=True, default='-')
    questions4       = models.CharField(max_length=200, null=True, blank=True, default='-')
    questions5       = models.CharField(max_length=200, null=True, blank=True, default='-')
    questions6       = models.CharField(max_length=200, null=True, blank=True, default='-')
    questions7       = models.CharField(max_length=200, null=True, blank=True, default='-')
    questions8       = models.CharField(max_length=200, null=True, blank=True, default='-')
    questions9       = models.CharField(max_length=200, null=True, blank=True, default='-')
    questions10      = models.CharField(max_length=200, null=True, blank=True, default='-')
    # questions11      = models.CharField(max_length=200, null=True, blank=True)
    questions12      = models.CharField(max_length=200, null=True, blank=True, default='-')
    questions13      = models.CharField(max_length=200, null=True, blank=True, default='-')
    # questions14      = models.CharField(max_length=200, null=True, blank=True)
    questions15      = models.CharField(max_length=200, null=True, blank=True, default='-')
    questions16      = models.CharField(max_length=200, null=True, blank=True, default='-')
    # questions17      = models.CharField(max_length=200, null=True, blank=True)
    # questions18      = models.CharField(max_length=200, null=True, blank=True)
    Q19temps_a_contacter = models.CharField(max_length=200, null=True, blank=True, default='-')
    montant_de_pret                     = models.CharField(max_length=100, null=True, blank=True, default='-')
    duree_de_credit                     = models.CharField(max_length=100, null=True, blank=True, default='-')
    montant_a_rembourser_chaque_mois    = models.CharField(max_length=100, null=True, blank=True, default='-')
    montant_des_ventes_bonne_journee    = models.CharField(max_length=100, null=True, blank=True, default='-')
    montant_des_ventes_mauvaise_journee = models.CharField(max_length=100, null=True, blank=True, default='-')
    date_a_laquelle_recevoir_credit     = models.CharField(max_length=100, null=True, blank=True, default='-')
    Nom_du_garant   = models.CharField(max_length=100, null=True, blank=True, default='-')
    Activite        = models.CharField(max_length=100, null=True, blank=True, default='-')
    Statut          = models.CharField(max_length=30, choices=STATUTS, null=True, blank=True, default='-')
    Commentaire     = models.TextField(null=True, blank=True, default='-')
    Concurrent      = models.TextField(null=True, blank=True, default='-')
    CommentaireQ17  = models.TextField(null=True, blank=True, default='-')
    campaignname      = models.CharField(max_length=200, null=True, default='-')

renouvellement/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages  # for message
from django.urls import reverse
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import JsonResponse
import xlwt
import csv
from django.forms.models import model_to_dict

from django.views.generic import View, DetailView
from scripting.utils import render_to_pdf
from django.template.loader import get_template

from renouvellement.models import Renouvellement
from renouvellement.forms import RenouvellementForm

from contacts.models import Contact
from contacts.forms import ContactForm

# Create your views here.
@login_required
def renouvellement_add(request):
    """
        Fonction Add new object
    """
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RenouvellementForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            renouvellement = form.save(commit=False)
            renouvellement.user = request.user
            renouvellement.save()
            messages.success(request, "Renouvellement de crédit enregistrée!")
            # redirect to a new URL:
            return HttpResponseRedirect(reverse('renouvellement:renouvellement_list'))
    # if a GET (or any other method) we'll create a blank form
    else:
        form = RenouvellementForm()

    if request.method == 'POST':
        if request.is_ajax():
            formContact = ContactForm(request.POST)
            if formContact.is_valid():
                    formContact.cleaned_data
                    formContact.user = request.user
                    formContact.save()
                    latest = Contact.objects.latest('id').id
                    contact_object = model_to_dict(Contact.objects.get(pk=latest))  
                
                    return JsonResponse({'error': False, 'data': contact_object})
            else:
                    print(formContact.errors)
                    return JsonResponse({'error': True, 'data': formContact.errors})
        else:
                error = {
                    'message': 'Error, must be an Ajax call.'
                }
                return JsonResponse(error, content_type="application/json")
    else:
        formContact = ContactForm()

        context = {
            'form': form,
            'formContact': formContact
        }
        template_name = 'pages/renouvellement/renouvellement_add.html'
        return render(request, template_name, context)



@login_required
def renouvellement_list(request): 
    """
        Fonction List objects
    """ 
    user = request.user
    renouvellement_count = Renouvellement.objects.filter(user=user).order_by('-created_date').count()
    renouvellement = Renouvellement.objects.filter(user=user).order_by('-created_date')
    paginator = Paginator(renouvellement, 10)
    page = request.GET.get('page')
    try:
        renouvellement_list = paginator.page(page)
    except PageNotAnInteger:
        renouvellement_list = paginator.page(1)
    except EmptyPage:
        renouvellement_list = paginator.page(paginator.num_pages)

    context = {
        'renouvellement_list': renouvellement_list,
        'renouvellement_count': renouvellement_count
    }  
    template_name = 'pages/renouvellement/renouvellement_list.html'
    return render(request, template_name, context)    



@login_required
def renouvellement_view(request, id):  
    """
        Fonction Detail
    """
    user = request.user
    renouvellement = Renouvellement.objects.filter(user=user).get(id=id)
    context = {
        'renouvellement': renouvellement,
    }  
    template_name = 'pages/renouvellement/renouvellement_view.html'
    return render(request, template_name, context)   



@login_required
def renouvellement_update(request, id):
    """
        Fonction de Mis à jour
    """
    renouvellement = Renouvellement.objects.get(id=id)
    form = RenouvellementForm(request.POST, instance=renouvellement)
    if form.is_valid():  
        form.user = request.user
        form.save()  
        messages.success(request, "Renouvellement modifié!")
        return redirect('renouvellement:renouvellement_list') 

    context = {
        'renouvellement': renouvellement,
        'form': form
    }  
    template_name = 'pages/renouvellement/renouvellement_update.html'
    return render(request, template_name, context)   



@login_required
def renouvellement_destroy(request, id):
    """
        Fonction de Suppresion
    """
    user = request.user
    renouvellement = Renouvellement.objects.filter(user=user).get(id=id)  
    renouvellement.delete()  
    return redirect("renouvellement:renouvellement_list")  




def export_renouvellement_xls(request):
    user = request.user
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="renouvellement.xls"'

    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Renouvellement')

    # Sheet header, first row
    row_num = 0

    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    columns = ['id', 'questions1', 'questions2', 'questions3', 'questions4', 'questions5', 'questions6', 'questions7', 'questions8', 'questions9',
        'questions10', 'questions12', 'questions13', 'questions15', 'questions16', 'Q19temps_a_contacter',
        'montant_de_pret', 'duree_de_credit', 'montant_a_rembourser_chaque_mois', 'montant_des_ventes_bonne_journee',
        'montant_des_ventes_mauvaise_journee', 'date_a_laquelle_recevoir_credit', 'Nom_du_garant', 'Activite',
        'Commentaire', 'Concurrent', 'CommentaireQ17', 'Statut',]

    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    # Sheet body, remaining rows
    font_style = xlwt.XFStyle()

    rows = Renouvellement.objects.filter(user=user).values_list(
        'id', 'questions1', 'questions2', 'questions3', 'questions4', 'questions5', 'questions6', 'questions7', 'questions8', 'questions9',
        'questions10', 'questions12', 'questions13', 'questions15', 'questions16', 'Q19temps_a_contacter',
        'montant_de_pret', 'duree_de_credit', 'montant_a_rembourser_chaque_mois', 'montant_des_ventes_bonne_journee',
        'montant_des_ventes_mauvaise_journee', 'date_a_laquelle_recevoir_credit', 'Nom_du_garant', 'Activite',
        'Commentaire', 'Concurrent', 'CommentaireQ17', 'Statut',)
    for row in rows:
        row_num += 1
        for col_num in range(len(row)):
            ws.write(row_num, col_num, row[col_num], font_style)

    wb.save(response)
    return response



def export_renouvellement_csv(request):
    user = request.user
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="dat.csv"'

    writer = csv.writer(response)
    writer.writerow(['id', 'questions1', 'questions2', 'questions3', 'questions4', 'questions5', 'questions6', 'questions7', 'questions8', 'questions9',
        'questions10', 'questions12', 'questions13', 'questions15', 'questions16', 'Q19temps_a_contacter',
        'montant_de_pret', 'duree_de_credit', 'montant_a_rembourser_chaque_mois', 'montant_des_ventes_bonne_journee',
        'montant_des_ventes_mauvaise_journee', 'date_a_laquelle_recevoir_credit', 'Nom_du_garant', 'Activite',
        'Commentaire', 'Concurrent', 'CommentaireQ17', 'Statut',])

    renouvellement = Renouvellement.objects.filter(user=user).values_list('id', 'questions1', 'questions2', 'questions3', 'questions4', 'questions5', 'questions6', 'questions7', 'questions8', 'questions9',
        'questions10', 'questions12', 'questions13', 'questions15', 'questions16', 'Q19temps_a_contacter',
        'montant_de_pret', 'duree_de_credit', 'montant_a_rembourser_chaque_mois', 'montant_des_ventes_bonne_journee',
        'montant_des_ventes_mauvaise_journee', 'date_a_laquelle_recevoir_credit', 'Nom_du_garant', 'Activite',
        'Commentaire', 'Concurrent', 'CommentaireQ17', 'Statut',)
    for renouvellement in renouvellement:
        writer.writerow(renouvellement)

    return response


class Export_Renouvellement_pdf(DetailView):
    """
        For detail to pdf based function
    """
    model = Renouvellement
    def get(self, request, *args, **kwargs):
        renouvellement = Renouvellement.objects.get(id=self.kwargs.get('id'))
        data = {
            'renouvellement': renouvellement,
            # 'today': datetime.date.today(), 
        }
        pdf = render_to_pdf('pages/renouvellement/renouvellement_pdf.html', data)
        return HttpResponse(pdf, content_type='application/pdf')

templates/pages/renouvellement/renouvellement_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} renouvellement de credit{% endblock title %}


{% block content %}

<!-- Page-header start -->
<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-8">
                <div class="page-header-title">SCRIPTING RENOUVELLEMENT DU CREDIT</h5>
                    <p class="m-b-0">Renouvellement du crédit</p>
                </div>
            </div>
            <div class="col-md-4">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{% url 'dashboard:dashboard' %}"> <i class="fa fa-home"></i> </a>
                    </li>
                    <li class="breadcrumb-item"><a href="#!">SCRIPTING RENOUVELLEMENT DU CREDIT</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- Page-header end -->

<div class="pcoded-inner-content">
    <!-- Main-body start -->
    <div class="main-body">
        <div class="page-wrapper">
            <!-- Page-body start -->
            <div class="page-body">
                {% include 'notifications/_alerts.html' %}
                <!-- Hover table card start -->
                <div class="row d-flex justify-content-end mb-4">
                    <button type="button" class="btn btn-primary">
                        <a href="{% url 'renouvellement:renouvellement_add' %}" style="color: aliceblue;font-weight: 700;">NOUVEAU</a>
                    </button>
                    <div class="dropdown ml-2">
                        <a class="btn btn-info dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            REPORTING
                        </a>
                
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'renouvellement:export_renouvellement_xls' %}">Excel</a>
                            <a class="dropdown-item" href="{% url 'renouvellement:export_renouvellement_csv' %}">CSV</a>
                            <a class="dropdown-item" href="#">PDF</a>
                            <a class="dropdown-item" href="#">JSON</a>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">
                        <h5>SCRIPTING RENOUVELLEMENT DU CREDIT</h5>
                        <div class="card-header-right">
                            <ul class="list-unstyled card-option">
                                <li><i class="fa fa fa-wrench open-card-option"></i></li>
                                <li><i class="fa fa-window-maximize full-card"></i></li>
                                <li><i class="fa fa-minus minimize-card"></i></li>
                                <li><i class="fa fa-refresh reload-card"></i></li>
                                <li><i class="fa fa-trash close-card"></i></li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-block table-border-style">
                        <div class="table-responsive">
                            <table class="table caption-top table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th scope="col">renouvellemente_de_création</th>
                                        <th>Nom</th>
                                        <th>Post_Nom</th>
                                        <th>Prénom</th>
                                        <th>Adresse</th>
                                        <th>Province</th>
                                        <th>Téléphone_1</th>
                                        <th>Email</th>
                                        <th>Statut</th>
                                        <th>Remarques</th>
                                        <th>Commentaires</th>
                                        <th>Questions_1</th>
                                        <th>Questions_2</th>
                                        <th>Questions_3</th>
                                        <th>Questions_4</th>
                                        <th>Questions_5</th>
                                        <th>Questions_7</th>
                                        <th>Questions_8</th>
                                        <th>Questions_9</th>
                                        <th>Questions_10</th>
                                        <th>Questions_12</th>
                                        <th>Questions_13</th>
                                        <th>Questions_15</th>
                                        <th>Questions_16</th>
                                        <th>Commentaire_Q17</th>
                                        <th>Concurrent</th>
                                        <th>Temps_à_recontacter</th>
                                        <th>Montant_de_prêt</th>
                                        <th>Durée_de_crédit</th>
                                        <th>Montant_à_rembourser_chaque_mois</th>
                                        <th>Montant_des_ventes_bonne_journée</th>
                                        <th>Montant_des_ventes_mauvaise_journée</th>
                                        <th>renouvellemente_à_laquelle_recevoir_le_credit</th>
                                        <th>Nom_du_garant</th>
                                        <th>Activité</th>
                                    </tr>
                                </thead>
                                <tbody>

                                    {% for renouvellement in renouvellement_list %}
                                    <tr>
                                        <td scope="row">
                                            <a href="{% url 'renouvellement:export_renouvellement_pdf' renouvellement.id %}" target="_blank">
                                                {{renouvellement.created_date}}
                                            </a>
                                        </td>
                                        <td>{{renouvellement.Contact.Nom}}</td>
                                        <td>{{renouvellement.Contact.Post_Nom}}</td>
                                        <td>{{renouvellement.Contact.Prenom}}</td>
                                        <td>N°{{renouvellement.Contact.Numero}} {{renouvellement.Contact.Rue}} {{renouvellement.Contact.Quartier}} {{renouvellement.Contact.Commune}}</td>
                                        <td>{{renouvellement.Contact.Ville}}</td>
                                        <td>{{renouvellement.Contact.Province}}</td>
                                        <td>{{renouvellement.Contact.phonenumber}}</td>
                                        <td>{{renouvellement.Contact.Email}}</td>
                                        <td>{{renouvellement.Statut}}</td>
                                        <td>{{renouvellement.Contact.Remarque}}</td>
                                        <td>{{renouvellement.Commentaire}}</td>
                                        <td>{{renouvellement.questions1}}</td>
                                        <td>{{renouvellement.questions2}}</td>
                                        <td>{{renouvellement.questions3}}</td>
                                        <td>{{renouvellement.questions4}}</td>
                                        <td>{{renouvellement.questions5}}</td>
                                        <td>{{renouvellement.questions7}}</td>
                                        <td>{{renouvellement.questions8}}</td>
                                        <td>{{renouvellement.questions9}}</td>
                                        <td>{{renouvellement.questions10}}</td>
                                        <td>{{renouvellement.questions12}}</td>
                                        <td>{{renouvellement.questions13}}</td>
                                        <td>{{renouvellement.questions15}}</td>
                                        <td>{{renouvellement.questions16}}</td>
                                        <td>{{renouvellement.CommentaireQ17}}</td>
                                        <td>{{renouvellement.Concurrent}}</td>
                                        <td>{{renouvellement.Q19temps_a_contacter}}</td>
                                        <td>{{renouvellement.montant_de_pret}}</td>
                                        <td>{{renouvellement.duree_de_crédit}}</td>
                                        <td>{{renouvellement.montant_a_rembourser_chaque_mois}}</td>
                                        <td>{{renouvellement.montant_des_ventes_bonne_journée}}</td>
                                        <td>{{renouvellement.montant_des_ventes_mauvaise_journee}}</td>
                                        <td>{{renouvellement.renouvellemente_a_laquelle_recevoir_credit}}</td>
                                        <td>{{renouvellement.Nom_du_garant}}</td>
                                        <td>{{renouvellement.Activite}}</td>
                                        <td>
                                            <a href="{% url 'renouvellement:renouvellement_uprenouvellemente' renouvellement.id %} ">
                                                <i class="fa fa-edit"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    {% endfor %}

                                </tbody>
                            </table>
                        </div>
                        <div class="d-flex justify-content-start">
                            <p>Total: {{renouvellement_count}} </p>
                        </div>
                        
                        <nav class="mb-50">
                            {% if renouvellement_list.has_other_pages %}
                            <ul class="pagination justify-content-center">
                                {% if renouvellement_list.has_previous %}
                                    <li class="page-item"><a class="page-link" href="?page={{ renouvellement_list.previous_page_number }}">&laquo;</a></li>
                                {% else %}
                                    <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
                                {% endif %}
                                {% for i in renouvellement_list.paginator.page_range %}
                                    {% if renouvellement_list.number == i %}
                                        <li class="page-item active">
                                            <span class="page-link">
                                                {{ i }}
                                                <span class="sr-only">(current)</span>
                                            </span>
                                        </li>
                                    {% else %}
                                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                    {% endif %}
                                {% endfor %}
                                {% if renouvellement_list.has_next %}
                                    <li class="page-item"><a class="page-link" href="?page={{ renouvellement_list.next_page_number }}">&raquo;</a></li>
                                {% else %}
                                    <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
                                {% endif %}
                            </ul>
                            {% endif %}
                        </nav>
                    </div>
                </div>
                <!-- Hover table card end -->
            </div>
            <!-- Page-body end -->
        </div>
    </div>
    <!-- Main-body end -->

    <div id="styleSelector"></div>
</div>


<div id="styleSelector"> </div>
</div>
</div>

{% endblock content %}