app/urls.py
from django.urls import path

from app.views import index_view


urlpatterns = [
    path('', index_view, name='index'),
]

dashboard/urls.py
from django.urls import path

from dashboard.views import dashboard_view, dashboard_admin_view

app_name= 'dashboard'

urlpatterns = [
    path('', dashboard_view, name='dashboard'),
    path('dashboard_admin_view/', dashboard_admin_view, name='dashboard_admin_view'),
]

dat/urls.py
from django.urls import path

from dat.views import (dat_add, dat_list, dat_update, dat_view, 
                       dat_destroy, export_dat_xls, export_dat_csv, Export_Dat_pdf)

app_name= 'dat'

urlpatterns = [
    path('dat-add/', dat_add, name='dat_add'),
    path('dat-list/', dat_list, name='dat_list'),
    path('dat-update/<int:id>/', dat_update, name='dat_update'),
    path('dat-view/<int:id>/', dat_view, name='dat_view'),
    path('dat-destroy/<int:id>/', dat_destroy, name='dat_destroy'),
    path('export/xls/', export_dat_xls, name='export_dat_xls'),
    path('export/csv/', export_dat_csv, name='export_dat_csv'),
    path('export/pdf/<int:id>/', Export_Dat_pdf.as_view(), name='export_dat_pdf'),
]

recouvrement/urls.py
from django.urls import path

from recouvrement.views import (
    recouvrement_add, recouvrement_list, 
    recouvrement_view, recouvrement_update, 
    recouvrement_destroy, export_recouvrement_xls, export_recouvrement_csv, Export_Recouvrement_pdf)

app_name= 'recouvrement'

urlpatterns = [
    path('recouvrement_add/', recouvrement_add, name='recouvrement_add'),
    path('recouvrement_list/', recouvrement_list, name='recouvrement_list'),
    path('recouvrement_view/<int:id>/', recouvrement_view, name='recouvrement_view'),
    path('recouvrement_update/<int:id>/', recouvrement_update, name='recouvrement_update'),
    path('recouvrement_destroy/<int:id>/', recouvrement_destroy, name='recouvrement_destroy'),
    path('export/xls/', export_recouvrement_xls, name='export_recouvrement_xls'),
    path('export/csv/', export_recouvrement_csv, name='export_recouvrement_csv'),
    path('export/pdf/<int:id>/', Export_Recouvrement_pdf.as_view(), name='export_recouvrement_pdf'),
]

scripting/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from scripting.search import GlobalSearchAPIView


handler400 = 'scripting.views_errors_page.handler400'
handler403 = 'scripting.views_errors_page.handler403'
handler404 = 'scripting.views_errors_page.handler404'
handler500 = 'scripting.views_errors_page.handler500'
handler503 = 'scripting.views_errors_page.handler503'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('api/', GlobalSearchAPIView.as_view()),
    path('app/', include('app.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('forms/', include('forms.urls')),
    path('pbx/', include('pbx.urls')),
    path('agenda/', include('agenda.urls')),
    path('dat/', include('dat.urls')),
    path('acquisition/', include('acquisition.urls')),
    path('commprom/', include('commprom.urls')),
    path('comptedormant/', include('comptedormant.urls')),
    path('recouvrement/', include('recouvrement.urls')),
    path('renouvellement/', include('renouvellement.urls')),
    path('contacts/', include('contacts.urls')),
    path('issabel/', include('issabel.urls')),
    path('param/', include('paramurl.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_ROOT,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
  

recouvrement/models.py
from django.db import models
from django.contrib.auth.models import User

from contacts.models import Contact
from forms.statut import STATUTS

# Create your models here.
class Recouvrement(models.Model):
    user             = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date     = models.DateTimeField(auto_now_add=True)
    questions1       = models.CharField(max_length=200, null=True, default='-')
    questions2       = models.CharField(max_length=200, null=True, default='-')
    Contact          = models.ForeignKey(Contact, on_delete=models.CASCADE)
    Statut           = models.CharField(max_length=30, choices=STATUTS, null=True)
    Bound            = models.CharField(max_length=20, null=True)
    campaignname      = models.CharField(max_length=200, null=True, default='-')

    def __str__(self):
        return self.questions1

recouvrement/forms.py
from django import forms

from recouvrement.models import Recouvrement

from contacts.models import Contact
from forms.statut import STATUTS

class RecouvrementForm(forms.ModelForm):
    class Meta:
        model = Recouvrement
        fields = (
            'questions1', 'questions2', 'Statut', 'Bound', 'Contact', 'campaignname',
        )

    questions1 = forms.CharField(
        label='',
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "name": "questons1"
            }
        )
    )

    questions2 = forms.CharField(
        label='',
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "name": "questons2"
            }
        )
    )

    Contact = forms.ModelChoiceField(
        label='',
        required=False,
        queryset=Contact.objects.all().order_by('-created_date'),
        widget=forms.Select(
            attrs={
                "id": "inputState",
                "class": "form-control",
                "placeholder": "Hopital"
            }
        )
    )

    Statut = forms.ChoiceField(
        label='',
        required=True,
        choices=STATUTS,
        widget=forms.Select(
            attrs={
                "class": "form-control",
                "name": "Statut",
            }
        )
    )

    Remarque = forms.CharField(
        label = '',
        required = False,
        widget = forms.TextInput(
            attrs={
                "class": "form-control",
                "name": "Remarque",
            }
        )
    )

    campaignname = forms.CharField(
        label = '',
        required = True,
        widget = forms.TextInput(
            attrs={
                "class": "form-control",
                "name":"campaignname",
            }
        )
    )

recouvrement/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages  # for message
from django.urls import reverse
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import JsonResponse
from django.forms.models import model_to_dict
import xlwt
import csv

from django.views.generic import View, DetailView
from scripting.utils import render_to_pdf
from django.template.loader import get_template

from recouvrement.models import Recouvrement
from recouvrement.forms import RecouvrementForm

from contacts.models import Contact
from contacts.forms import ContactForm

# Create your views here.
@login_required
def recouvrement_add(request):
    """
        Fonction Add new object
    """
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RecouvrementForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            recouvrement = form.save(commit=False)
            recouvrement.user = request.user
            recouvrement.save()
            messages.success(request, "Recouvrement enregistrée!")
            # redirect to a new URL:
            return HttpResponseRedirect(reverse('recouvrement:recouvrement_list'))
    # if a GET (or any other method) we'll create a blank form
    else:
        form = RecouvrementForm()

    if request.method == 'POST':
        if request.is_ajax():
            formContact = ContactForm(request.POST)
            if formContact.is_valid():
                    formContact.cleaned_data
                    formContact.user = request.user
                    formContact.save()
                    latest = Contact.objects.latest('id').id
                    contact_object = model_to_dict(Contact.objects.get(pk=latest))  
                
                    return JsonResponse({'error': False, 'data': contact_object})
            else:
                    print(formContact.errors)
                    return JsonResponse({'error': True, 'data': formContact.errors})
        else:
                error = {
                    'message': 'Error, must be an Ajax call.'
                }
                return JsonResponse(error, content_type="application/json")
    else:
        formContact = ContactForm()

        context = {
            'form': form,
            'formContact': formContact
        }
        template_name = 'pages/recouvrement/recouvrement_add.html'
        return render(request, template_name, context)



@login_required
def recouvrement_list(request): 
    """
        Fonction List objects
    """ 
    user = request.user
    commprom_count = Recouvrement.objects.filter(user=user).order_by('-created_date').count
    recouvrement = Recouvrement.objects.filter(user=user).order_by('-created_date')
    paginator = Paginator(recouvrement, 10)
    page = request.GET.get('page')
    try:
        recouvrement_list = paginator.page(page)
    except PageNotAnInteger:
        recouvrement_list = paginator.page(1)
    except EmptyPage:
        recouvrement_list = paginator.page(paginator.num_pages)

    context = {
        'recouvrement_list': recouvrement_list,
        'commprom_count': commprom_count,
    }  
    template_name = 'pages/recouvrement/recouvrement_list.html'
    return render(request, template_name, context)    



@login_required
def recouvrement_view(request, id):  
    """
        Fonction Detail
    """
    user = request.user
    recouvrement = Recouvrement.objects.filter(user=user).get(id=id)
    context = {
        'recouvrement': recouvrement,
    }  
    template_name = 'pages/recouvrement/recouvrement_view.html'
    return render(request, template_name, context)   



@login_required
def recouvrement_update(request, id):
    """
        Fonction de Mis à jour
    """
    recouvrement = Recouvrement.objects.get(id=id)  
    form = RecouvrementForm(request.POST, instance=recouvrement)  
    if form.is_valid():  
        form.user = request.user
        form.save()  
        messages.success(request, "Recouvrement modifié!")
        return redirect('recouvrement:recouvrement_list') 
    context = {
        'recouvrement': recouvrement,
        'form': form
    }  
    template_name = 'pages/recouvrement/recouvrement_update.html'
    return render(request, template_name, context)   



@login_required
def recouvrement_destroy(request, id):
    """
        Fonction de Suppresion
    """
    user = request.user
    recouvrement = Recouvrement.objects.filter(user=user).get(id=id)  
    recouvrement.delete()  
    return redirect("recouvrement:recouvrement_list")  




def export_recouvrement_xls(request):
    user = request.user
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="recouvrement.xls"'

    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('recouvrement')

    # Sheet header, first row
    row_num = 0

    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    columns = ['user', 'questions1', 'questions2', 'Statut', 'Bound', 'Contact']

    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    # Sheet body, remaining rows
    font_style = xlwt.XFStyle()

    rows = Recouvrement.objects.filter(user=user).values_list(
        'user', 'questions1', 'questions2', 'Statut', 'Bound', 'Contact')
    for row in rows:
        row_num += 1
        for col_num in range(len(row)):
            ws.write(row_num, col_num, row[col_num], font_style)

    wb.save(response)
    return response


def export_recouvrement_csv(request):
    user = request.user
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="recouvrement.csv"'

    writer = csv.writer(response)
    writer.writerow(['user', 'created_date', 'questions1', 'questions2', 'Statut', 'Bound', 'Contact'])

    recouvrement = Recouvrement.objects.filter(user=user).values_list('user', 'created_date', 'questions1', 'questions2', 'Statut', 'Bound', 'Contact')
    for recouvrement in recouvrement:
        writer.writerow(recouvrement)

    return response

class Export_Recouvrement_pdf(DetailView):
    """
        For detail to pdf based function
    """
    model = Recouvrement
    def get(self, request, *args, **kwargs):
        recouvrement = Recouvrement.objects.get(id=self.kwargs.get('id'))
        data = {
            'recouvrement': recouvrement,
            # 'today': datetime.date.today(), 
        }
        pdf = render_to_pdf('pages/recouvrement/recouvrement_pdf.html', data)
        return HttpResponse(pdf, content_type='application/pdf')

templates/pages/recouvrement/recouvrement_js.html
<script type="text/javascript">
    $(document).ready(function () {
        $('#outbound').hide();
        $('#inbound').hide();
        // Traffic Bound
        $("input[name=bound]").change(function () {
            if ($("#OUTBOUND").is(':checked')) {
                $('#outbound').show();
                $('#inbound').hide();
            } else if ($("#INBOUND").is(':checked')) {
                $('#outbound').hide();
                $('#inbound').show();
            }
        });
    });


    $(document).ready(function () {
        $('#q2').hide();
        $('#q3').hide();
        $('#q4').hide();

        // Traffic OUTBOUND
        $("input[name='questions1']").click(function () {
            if ($('input:radio[qs=q1OUI]').is(':checked')) {
                $('#q2').show();
            } else if ($('input:radio[qs=q1NON]').is(':checked')) {
                $('#q2').hide();
                $('#q3').hide();
                $('#q4').show();
            }
        });

        $("input[name='questions2']").click(function () {
            if ($('input:radio[qs=q2OUI]').is(':checked')) {
                $('#q3').show();
                $('#q4').show();
            } else if ($('input:radio[qs=q2NON]').is(':checked')) {
                $('#q3').hide();
                $('#q4').show();
            }
        });
    });

    $(document).ready(function () {
        $('#qb2').hide();
        $('#qb3').hide();
        $('#qb4').hide();

        // Traffic OUTBOUND
        $("input[name='questions1']").click(function () {
            if ($('input:radio[qin=qb1OUI]').is(':checked')) {
                $('#qb2').show();
            } else if ($('input:radio[qin=qb1NON]').is(':checked')) {
                $('#qb2').hide();
                $('#qb3').hide();
                $('#qb4').show();
            }
        });

        $("input[name='questions2']").click(function () {
            if ($('input:radio[qin=qb2OUI]').is(':checked')) {
                $('#qb3').show();
                $('#qb4').show();
            } else if ($('input:radio[qin=qb2NON]').is(':checked')) {
                $('#qb3').hide();
                $('#qb4').show();
            }
        });
    });



    // Get DOM Elements
        const modal = document.querySelector('#my-modal');
        const modalBtn = document.querySelector('#modal-btn');
        const closeBtn = document.querySelector('#close');

        // Events
        modalBtn.addEventListener('click', openModal);
        closeBtn.addEventListener('click', closeModal);
        window.addEventListener('click', outsideClick);

        // Open
        function openModal() {
            modal.style.display = 'block';
        }

        // Close
        function closeModal() {
            modal.style.display = 'none';
        }

        // Close If Outside Click
        function outsideClick(e) {
            if (e.target == modal) {
                modal.style.display = 'none';
            }
        }



        $(document).ready(function () {
            $('#contact-form').submit(function (e) {
                e.preventDefault();
                var formData = {
                    'Nom': $('#Nom').val(),
                    'Post_Nom': $('#Post_Nom').val(),
                    'Prenom': $('#Prenom').val(),
                    'Numero': $('#Numero').val(),
                    'Rue': $('#Rue').val(),
                    'Quartier': $('#Quartier').val(),
                    'Commune': $('#Commune').val(),
                    'Ville': $('#Ville').val(),
                    'Province': $('#Province').val(),
                    'phonenumber': $('#phonenumber').val(),
                    'Tel2': $('#Tel2').val(),
                    'Tel3': $('#Tel3').val(),
                    'Email': $('#Email').val(),
                    'Website': $('#Website').val(),
                    'Facebook': $('#Facebook').val(),
                    'Instagram': $('#Instagram').val(),
                    'Twitter': $('#Twitter').val(),
                    'LinkedIn': $('#LinkedIn').val(),
                    'Remarque': $('#Remarque').val(),
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                    contentType: 'application/x-www-form-urlencoded',
                    encode: true,
                };
                $.ajax({
                    type: 'POST',
                    url: "{% url 'recouvrement:recouvrement_add' %}",
                    data: formData,
                    dataType: 'json',
                }).done(function (data) {
                    // console.log(formData);
                    $("#contact-form").trigger("reset");
                    // console.log(data)


                    $('#kycContact').each(function () {
                        setTimeout(10000);
                    });
                });



                // e.preventDefault();
            });
        });



    // function refresh() {
    //     $.ajax({
    //         url: "{% url 'dat:dat_add' %}",
    //         success: function (data) {
    //             $('#kycContact').html(data);
    //             setTimeout(refresh, 10000);
    //         }

    //     });
    // }

</script>

templates/pages/recouvrement/recouvrement_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Recrouvrement Liste scripting {% endblock title %}


{% block content %}

<!-- Page-header start -->
<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-8">
                <div class="page-header-title">
                    <h5 class="m-b-10">RECROUVREMENT</h5>
                    <p class="m-b-0">Liste des Scripting</p>
                </div>
            </div>
            <div class="col-md-4">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{% url 'dashboard:dashboard' %}"> <i class="fa fa-home"></i> </a>
                    </li>
                    <li class="breadcrumb-item"><a href="#!">RECROUVREMENT</a></li>
                    <li class="breadcrumb-item"><a href="#!">Listes</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- Page-header end -->

<div class="pcoded-inner-content">
    <!-- Main-body start -->
    <div class="main-body">
        <div class="page-wrapper">
            <!-- Page-body start -->
            <div class="page-body">
                {% include 'notifications/_alerts.html' %}
                <!-- Hover table card start -->
                <div class="row d-flex justify-content-end mb-4">
                    <button type="button" class="btn btn-primary">
                        <a href="{% url 'recouvrement:recouvrement_add' %}" style="color: aliceblue;font-weight: 700;">NOUVEAU</a>
                    </button>
                    <div class="dropdown ml-2">
                        <a class="btn btn-info dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            REPORTING
                        </a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'recouvrement:export_recouvrement_xls' %}">Excel</a>
                            <a class="dropdown-item" href="{% url 'recouvrement:export_recouvrement_csv' %}">CSV</a>
                            <a class="dropdown-item" href="#">PDF</a>
                            <a class="dropdown-item" href="#">JSON</a>
                        </div>
                    </div>
                </div> 
                <div class="card">
                    <div class="card-header">
                        <h5>RECROUVREMENT OUTBOUND-INBOUND</h5>
                        <div class="card-header-right">
                            <ul class="list-unstyled card-option">
                                <li><i class="fa fa fa-wrench open-card-option"></i></li>
                                <li><i class="fa fa-window-maximize full-card"></i></li>
                                <li><i class="fa fa-minus minimize-card"></i></li>
                                <li><i class="fa fa-refresh reload-card"></i></li>
                                <li><i class="fa fa-trash close-card"></i></li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-block table-border-style">
                        <div class="table-responsive">
                            <table class="table caption-top table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th scope="col">Date_de_création</th>
                                        <th>Questions_1</th>
                                        <th>Questions_2</th>
                                        <th>Nom</th>
                                        <th>Post_Nom</th>
                                        <th>Prénom</th>
                                        <th>Adresse</th>
                                        <th>Ville</th>
                                        <th>Province</th>
                                        <th>Téléphone</th>
                                        <th>Email</th>
                                        <th>Statut</th>
                                        <th>Remarque</th>
                                        <th>Agent</th>
                                        <th>Bound</th>
                                    </tr>
                                </thead>
                                <tbody>

                                    {% for recouvrement in recouvrement_list %}
                                        <tr>
                                            <td scope="row">
                                                <a href="{% url 'recouvrement:export_recouvrement_pdf' recouvrement.id %}" target="_blank">
                                                    {{recouvrement.created_date}}
                                                </a>
                                            </td>
                                            <td>{{recouvrement.questions1}}</td>
                                            <td>{{recouvrement.questions2}}</td>
                                            <td>{{recouvrement.Contact.Nom}}</td>
                                            <td>{{recouvrement.Contact.Post_Nom}}</td>
                                            <td>{{recouvrement.Contact.Prenom}}</td>
                                            <td>N°{{recouvrement.Contact.Numero}} {{recouvrement.Contact.Rue}} {{recouvrement.Contact.Quartier}} {{recouvrement.Contact.Commune}}</td>
                                            <td>{{recouvrement.Contact.Ville}}</td>
                                            <td>{{recouvrement.Contact.Province}}</td>
                                            <td>{{recouvrement.Contact.phonenumber}}</td>
                                            <td>{{recouvrement.Contact.Email}}</td>
                                            <td>{{recouvrement.Statut}}</td>
                                            <td>{{recouvrement.Remarque}}</td>
                                            <td>{{recouvrement.user}}</td>
                                            <td>{{recouvrement.Bound}}</td>
                                            <td>
                                                <a href="{% url 'recouvrement:recouvrement_update' recouvrement.id %} ">
                                                    <i class="fa fa-edit"></i>
                                                </a>
                                            </td>
                                            <td>
                                                <a href="{% url 'recouvrement:recouvrement_destroy' recouvrement.id %} ">
                                                    <i class="bi bi-trash-fill"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    {% endfor %}

                                </tbody>
                            </table>
                        </div>
                        <div class="d-flex justify-content-start">
                            <p>Total: {{commprom_count}} </p>
                        </div>

                        <nav class="mb-50">
                            {% if recouvrement_list.has_other_pages %}
                                <ul class="pagination justify-content-center">
                                    {% if recouvrement_list.has_previous %}
                                        <li class="page-item"><a class="page-link"
                                            href="?page={{ recouvrement_list.previous_page_number }}">&laquo;</a></li>
                                    {% else %}
                                        <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
                                    {% endif %}
                                    {% for i in recouvrement_list.paginator.page_range %}
                                        {% if recouvrement_list.number == i %}
                                        <li class="page-item active">
                                            <span class="page-link">
                                                {{ i }}
                                                <span class="sr-only">(current)</span>
                                            </span>
                                        </li>
                                        {% else %}
                                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if recouvrement_list.has_next %}
                                        <li class="page-item"><a class="page-link"
                                                href="?page={{ recouvrement_list.next_page_number }}">&raquo;</a></li>
                                    {% else %}
                                        <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
                                    {% endif %}
                                </ul>
                            {% endif %}
                        </nav>

                    </div>
                </div>
                <!-- Hover table card end -->
            </div>
            <!-- Page-body end -->
        </div>
    </div>
    <!-- Main-body end -->

    <div id="styleSelector"></div>
</div>


<div id="styleSelector"> </div>
</div>
</div>

{% endblock content %}