acquisition/urls.py
from django.urls import path

from acquisition.views import (
    acquisition_add, acquisition_list,
     acquisition_update, acquisition_view, 
     acquisition_destroy, export_acquisition_xls, export_acquisition_csv, Export_Acquisition_pdf)

app_name = 'acquisition'

urlpatterns = [
    path('acquisition_add/', acquisition_add, name='acquisition_add'),
    path('acquisition_list/', acquisition_list, name='acquisition_list'),
    path('acquisition_update/<int:id>/', acquisition_update, name='acquisition_update'),
    path('acquisition_view/<int:id>/', acquisition_view, name='acquisition_view'),
    path('acquisition_destroy/<int:id>/', acquisition_destroy, name='acquisition_destroy'),
    path('export/xls/', export_acquisition_xls, name='export_acquisition_xls'),
    path('export/csv/', export_acquisition_csv, name='export_acquisition_csv'),
    path('export/pdf/<int:id>/', Export_Acquisition_pdf.as_view(), name='export_acquisition_pdf'),
]
 

app/urls.py
from django.urls import path

from app.views import index_view


urlpatterns = [
    path('', index_view, name='index'),
]

commprom/urls.py
from django.urls import path

from commprom.views import (commprom_add, 
        commprom_list, commprom_update, 
        commprom_view, commprom_destroy, 
        export_commprom_xls, 
        export_commprom_csv, Export_Commprom_pdf)

app_name= 'commprom'

urlpatterns = [
    path('commprom_add/', commprom_add, name='commprom_add'),
    path('commprom_list/', commprom_list, name='commprom_list'),
    path('commprom_update/<int:id>/', commprom_update, name='commprom_update'),
    path('commprom_view/<int:id>/', commprom_view, name='commprom_view'),
    path('commprom_destroy/<int:id>/', commprom_destroy, name='commprom_destroy'),
    path('export/xls/', export_commprom_xls, name='export_commprom_xls'),
    path('export/csv/', export_commprom_csv, name='export_commprom_csv'),
    path('export/pdf/<int:id>/', Export_Commprom_pdf.as_view(), name='export_commprom_pdf'),
]

dat/urls.py
from django.urls import path

from dat.views import (dat_add, dat_list, dat_update, dat_view, 
                       dat_destroy, export_dat_xls, export_dat_csv, Export_Dat_pdf)

app_name= 'dat'

urlpatterns = [
    path('dat-add/', dat_add, name='dat_add'),
    path('dat-list/', dat_list, name='dat_list'),
    path('dat-update/<int:id>/', dat_update, name='dat_update'),
    path('dat-view/<int:id>/', dat_view, name='dat_view'),
    path('dat-destroy/<int:id>/', dat_destroy, name='dat_destroy'),
    path('export/xls/', export_dat_xls, name='export_dat_xls'),
    path('export/csv/', export_dat_csv, name='export_dat_csv'),
    path('export/pdf/<int:id>/', Export_Dat_pdf.as_view(), name='export_dat_pdf'),
]

paramurl/urls.py
from django.urls import path

from paramurl.views import paramurl_view

app_name= 'param_url'

urlpatterns = [
    path('', paramurl_view),
]

recouvrement/urls.py
from django.urls import path

from recouvrement.views import (
    recouvrement_add, recouvrement_list, 
    recouvrement_view, recouvrement_update, 
    recouvrement_destroy, export_recouvrement_xls, export_recouvrement_csv, Export_Recouvrement_pdf)

app_name= 'recouvrement'

urlpatterns = [
    path('recouvrement_add/', recouvrement_add, name='recouvrement_add'),
    path('recouvrement_list/', recouvrement_list, name='recouvrement_list'),
    path('recouvrement_view/<int:id>/', recouvrement_view, name='recouvrement_view'),
    path('recouvrement_update/<int:id>/', recouvrement_update, name='recouvrement_update'),
    path('recouvrement_destroy/<int:id>/', recouvrement_destroy, name='recouvrement_destroy'),
    path('export/xls/', export_recouvrement_xls, name='export_recouvrement_xls'),
    path('export/csv/', export_recouvrement_csv, name='export_recouvrement_csv'),
    path('export/pdf/<int:id>/', Export_Recouvrement_pdf.as_view(), name='export_recouvrement_pdf'),
]

scripting/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from scripting.search import GlobalSearchAPIView


handler400 = 'scripting.views_errors_page.handler400'
handler403 = 'scripting.views_errors_page.handler403'
handler404 = 'scripting.views_errors_page.handler404'
handler500 = 'scripting.views_errors_page.handler500'
handler503 = 'scripting.views_errors_page.handler503'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('api/', GlobalSearchAPIView.as_view()),
    path('app/', include('app.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('forms/', include('forms.urls')),
    path('pbx/', include('pbx.urls')),
    path('agenda/', include('agenda.urls')),
    path('dat/', include('dat.urls')),
    path('acquisition/', include('acquisition.urls')),
    path('commprom/', include('commprom.urls')),
    path('comptedormant/', include('comptedormant.urls')),
    path('recouvrement/', include('recouvrement.urls')),
    path('renouvellement/', include('renouvellement.urls')),
    path('contacts/', include('contacts.urls')),
    path('issabel/', include('issabel.urls')),
    path('param/', include('paramurl.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_ROOT,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
  

paramurl/models.py
from django.db import models

# Create your models here.

paramurl/views.py
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseBadRequest
from django.shortcuts import render, redirect
from django.urls import reverse

from acquisition.models import Acquisition
from contacts.models import Contact
from commprom.models import Commprom
from comptedormant.models import Compte_dormant
from dat.models import Dat
from recouvrement.models import Recouvrement
from renouvellement.models import Renouvellement
# Create your views here.

def paramurl_view(request):
    # Get value
    phonenumber = request.GET.get('phonenumber', None)
    campaignname = request.GET.get('campaignname', None)

    # Campaign
    dat = 'dat',
    commprom = 'commprom',
    comptedormant = 'comptedormant',
    acquisition = 'acquisition',
    recouvrement = 'recouvrement',
    renouvellement = 'renouvellement',

    # campaigns = [dat, commprom, comptedormant, acquisition, recouvrement, renouvellement]

    if campaignname is not None:
    
        try:
            phone = Contact.objects.get(phonenumber=phonenumber)

            if phone is not None:

                if campaignname in acquisition:
                    acquisition_campaign = Acquisition.objects.filter(Contact=phone).filter(campaignname=campaignname).first()
                    
                    context = {
                        'acquisition_campaign': acquisition_campaign
                    }
                    template_name = 'pages/param_url/param_acquisition.html'
                    return render(request, template_name, context)

                elif campaignname in commprom:
                    commprom_campaign = Commprom.objects.filter(Contact=phone).filter(campaignname=campaignname).first()
                    context= {
                        'commprom_campaign': commprom_campaign
                    }
                    template_name = 'pages/param_url/param_commprom.html'
                    return render(request, template_name, context)

                elif campaignname in comptedormant:
                    comptedormant_campaign = Compte_dormant.objects.filter(Contact=phone).filter(campaignname=campaignname).first()
                    context = {
                        'comptedormant_campaign': comptedormant_campaign
                    }
                    template_name = 'pages/param_url/param_comptedormant.html'
                    return render(request, template_name, context)
                
                elif campaignname in dat:
                    dat_campaign = Dat.objects.filter(Contact=phone).filter(campaignname=campaignname).first()
                    # return HttpResponse('<h1>Dat numero {} {} {} </h1>'.format(phone, dat_campaign.id, dat_campaign.Statut))
                    context= {
                        'dat_campaign': dat_campaign
                    }
                    template_name = 'pages/param_url/param_dat.html'
                    return render(request, template_name, context)

                elif campaignname in recouvrement:
                    recouvrement_campaign = Recouvrement.objects.filter(Contact=phone).filter(campaignname=campaignname).first()
                    context = {
                        'recouvrement_campaign': recouvrement_campaign
                    }
                    template_name = 'pages/param_url/param_recouvrement.html'
                    return render(request, template_name, context)

                elif campaignname in renouvellement:
                    renouvellement_campaign = Renouvellement.objects.filter(Contact=phone).filter(campaignname=campaignname).first()
                    context = {
                        'renouvellement_campaign': renouvellement_campaign
                    }
                    template_name = 'pages/param_url/param_renouvellement.html'
                    return render(request, template_name, context)
                
                # else:
                #     return HttpResponse('<h1>La campaign n\'est pas trouvé</h1>')
        
        except Contact.DoesNotExist:
            return HttpResponse('<h1>Le contact n\'existe pas</h1>')
    else:
        template_name = 'pages/param_url/param_url.html'
        return render(request, template_name)

templates/pages/param_url/param_acquisition.html
{% extends 'base_params.html' %}
{% load static %}

{% block title %} ACQUISITION {% endblock title %}


{% block param_url %}

<div class="container my-5">
    <div class="card">
        <div class="card-header">
            <h6>CAMPAIGN <strong>{{acquisition_campaign.campaignname |upper}}</strong></h6>
            <div class="row">
                <h2>APPEL DE <strong>{{acquisition_campaign.Contact.phonenumber}}</strong></h2>
                <div class="d-flex justify-content-end">
                    <a href="{% url 'acquisition:acquisition_update' acquisition_campaign.id %}" role="button" class="btn btn-primary mr-2"
                        style="color: aliceblue;font-weight: 700;">
                        MODIFIER
                    </a>
                    <a class="btn btn-info" href="{% url 'acquisition:export_acquisition_pdf' acquisition_campaign.id %}" target="_blank">
                        PDF
                    </a>
                </div>
            </div>
        </div>

        <div class="card-body">
            <div class='details'>
                <p><strong>Questions 1</strong>: <br>
                    <i>J'aimerais vous poser quelques questions simples sur votre intérêt pour Advans ?</i>
                    <br>
                    R/ {{acquisition_campaign.questions1}}
                </p>
                <p><strong>Questions 2</strong>: <br>
                    <i>Permettez-moi de vérifier vos coordonnées (KYC)</i> <br>
                    <i><strong>Nom</strong>: {{acquisition_campaign.Contact.Nom}}</i> <br>
                    <i><strong>Post_Nom</strong>: {{acquisition_campaign.Contact.Post_Nom}}</i> <br>
                    <i><strong>Prénom</strong>: {{acquisition_campaign.Contact.Prenom}}</i> <br>
                    <i><strong>Adresse</strong>: N°{{acquisition_campaign.Contact.Numero}} {{acquisition_campaign.Contact.Rue}}
                        {{acquisition_campaign.Contact.Quartier}}
                        {{acquisition_campaign.Contact.Commune}}</i> <br>
                    <i><strong>Ville</strong>: {{acquisition_campaign.Contact.Ville}}</i> <br>
                    <i><strong>Province</strong>: {{acquisition_campaign.Contact.Province}}</i> <br>
                    <i><strong>Téléphone</strong>: {{acquisition_campaign.Contact.phonenumber}}</i> <br>
                    <i><strong>Email</strong>: {{acquisition_campaign.Contact.Email}}</i> <br>
                    <i><strong>Remarque</strong>: {{acquisition_campaign.Contact.Remarque}}</i> <br>
                </p>
                <p><strong>Questions 3</strong>: <br>
                    <i>Pouvez-vous m’indiquer lequel de nos services vous intéresse particulièrement ?</i>
                    <br> R/ {{acquisition_campaign.questions3}}
                </p>
                <p><strong>Questions 4</strong>: <br>
                    <i>Puis je vous proposer de rencontrer notre commercial en agence sur nos produits et services ?</i>
                    <br> R/ {{acquisition_campaign.questions4}}
                </p>
                <p><strong>Questions 5</strong>: <br>
                    <i>Quelles date et heure vous arrangent ?</i>
                    <br> R/ {{acquisition_campaign.questions5}}
                    <br>
                    <i><strong>Commentaires</strong>:
                        <br> R/ {{acquisition_campaign.CommentaireQ5}}
                    </i>
                </p>
                <p><strong>Questions 6</strong>: <br>
                    <i>AVEZ-VOUS DAUTRES QUESTIONS. Puis je vous proposer de rencontrer notre commercial en agence sur nos autres
                        produits et
                        services. Quelles date et heure vous arrangent ?</i>
                    <br> R/ {{acquisition_campaign.questions6}}
                    <br>
                    <i><strong>Commentaires</strong>:
                        <br> R/ {{acquisition_campaign.CommentaireQ6}}
                    </i>
                </p>
                <p><strong>Questions 7</strong>: <br>
                    <i>
                        Merci pour votre temps aujourd'hui. Nous espérons que vous pourriez toujours être intéressé par Advans à
                        l'avenir.
                    </i>
                    <br> R/ {{acquisition_campaign.Statut}}
                </p>
            
                <p><strong>Campaign name</strong>:
                    <br>
                    R/ {{acquisition_campaign.campaignname}}
                </p>
            
                <p><strong>Remplie par l'agent</strong>: {{acquisition_campaign.user}}</p>
                <!-- <p><strong>Bound</strong>: {{acquisition.Bound}}</p> -->
            </div>
        </div>
    </div>
</div>

{% endblock param_url %}

templates/pages/param_url/param_commprom.html
{% extends 'base_params.html' %}
{% load static %}

{% block title %} COMM & PROM {% endblock title %}


{% block param_url %}

<div class="container my-5">
    <div class="card">
        <div class="card-header">
            <h6>CAMPAIGN <strong>{{commprom_campaign.campaignname |upper}}</strong></h6>
            <div class="row">
                <h2>APPEL DE <strong>{{commprom_campaign.Contact.phonenumber}}</strong></h2>
                <div class="d-flex justify-content-end">
                    <a href="{% url 'commprom:commprom_update' commprom_campaign.id %}" role="button"
                        class="btn btn-primary mr-2" style="color: aliceblue;font-weight: 700;">
                        MODIFIER
                    </a>
                    <a class="btn btn-info"
                        href="{% url 'commprom:export_commprom_pdf' commprom_campaign.id %}" target="_blank">
                        PDF
                    </a>
                </div>
            </div>
        </div>

        <div class="card-body">
        <div class='details'>
            <p><strong>Questions 1</strong>: <br>
                <i>Nous souhaiterions parler avec Mr/Mme X</i>
                <br>
                R/ {{commprom_campaign.questions1}}
            </p>
            <p><strong>Questions 2</strong>: <br>
                <i>Nous souhaitons vous proposer notre nouvelle offre de service qui comprend les avantages suivants
                    (expliquer)...</i>
                <br> R/ {{commprom_campaign.questions2}}
            </p>
            <p><strong>Questions 3</strong>: <br>
                <i>Permettez-moi de vérifier vos coordonnées (KYC)</i> <br>
                <i><strong>Nom</strong>: {{commprom_campaign.Contact.Nom}}</i> <br>
                <i><strong>Post_Nom</strong>: {{commprom_campaign.Contact.Post_Nom}}</i> <br>
                <i><strong>Prénom</strong>: {{commprom_campaign.Contact.Prenom}}</i> <br>
                <i><strong>Adresse</strong>: N°{{commprom_campaign.Contact.Numero}} {{commprom_campaign.Contact.Rue}}
                    {{commprom_campaign.Contact.Quartier}}
                    {{commprom_campaign.Contact.Commune}}</i> <br>
                <i><strong>Ville</strong>: {{commprom_campaign.Contact.Ville}}</i> <br>
                <i><strong>Province</strong>: {{commprom_campaign.Contact.Province}}</i> <br>
                <i><strong>Téléphone</strong>: {{commprom_campaign.Contact.phonenumber}}</i> <br>
                <i><strong>Email</strong>: {{commprom_campaign.Contact.Email}}</i> <br>
                <i><strong>Remarque</strong>: {{commprom_campaign.Contact.Remarque}}</i> <br>
            </p>
            <p><strong>Questions 4</strong>: <br>
                <i>
                    Merci pour votre temps aujourd'hui. Nous espérons que vous pourriez toujours être intéressé par
                    Advans à l'avenir.
                </i>
                <br> R/ {{commprom_campaign.Statut}}
            </p>
            <p><strong>Type de trafic</strong>: {{commprom_campaign.Bound}}</p>

            <p><strong>Campaign name</strong>:
                <br>
                R/ {{commprom_campaign.campaignname}}
            </p>
        
        
            <p><strong>Remplie par l'agent</strong>: {{commprom_campaign.user}}</p>
        
        
        </div>
        </div>
    </div>
</div>



{% endblock param_url %}

templates/pages/param_url/param_comptedormant.html
{% extends 'base_params.html' %}
{% load static %}

{% block title %} COMPTE DORMANT {% endblock title %}


{% block param_url %}

<div class="container my-5">
    <div class="card">
        <div class="card-header">
            <h6>CAMPAIGN <strong>{{comptedormant_campaign.campaignname |upper}}</strong></h6>
            <div class="row">
                <h2>APPEL DE <strong>{{comptedormant_campaign.Contact.phonenumber}}</strong></h2>
                <div class="d-flex justify-content-end">
                    <a href="{% url 'compte_dormant:compte_dormant_update' comptedormant_campaign.id %}" role="button"
                        class="btn btn-primary mr-2" style="color: aliceblue;font-weight: 700;">
                        MODIFIER
                    </a>
                    <a class="btn btn-info"
                        href="{% url 'compte_dormant:compte_dormant_pdf' comptedormant_campaign.id %}" target="_blank">
                        PDF
                    </a>
                </div>
            </div>
        </div>

        <div class="card-body">
            <div class='details'>
                <p><strong>Questions 1</strong>: <br>
                    <i>Bonjour, c'est {{user.profile.sexe}} <strong>{{user.first_name|upper}}</strong> de Advans.
                    Nous souhaiterions parler avec Mr/Mme X</i>
                    <br>
                    R/ {{comptedormant_campaign.questions1}}
                </p>
                <p><strong>Questions 2</strong>: <br>
                    <i>
                        Je constate que vous n’opérez plus de mouvement sur votre compte depuis un certain temps.
                    </i>
                    <br>
                    R/ {{comptedormant_campaign.questions2}}
                </p>
                <p>
                    <i>
                        Puis-j ’en connaître la raison?
                    </i>
                    <br>
                    R/ {{comptedormant_campaign.Raison}}
                </p>
                <p><strong>Questions 3</strong>: <br>
                    <i>
                        Quand envisagez-vous d'alimenter votre compte ?
                    </i>
                    <!-- <i>
                        Avez-vous votre agenda pour fixer un RDV avec l’un de nos conseillers ?
                    </i> -->
                    <br>
                    R/ {{comptedormant_campaign.questions3}}
                </p>
                <p><strong>Questions 4</strong>: <br>
                    <i>
                        Quelle date vous convient pour alimenter ce compte. Plutôt le X ou le Y ; à telle heure ou plutôt à telle :
                    </i>
                    <br>
                    R/ {{comptedormant_campaign.questions4}}
                </p>
                <p><strong>Questions 5</strong>: <br>
                    <i>Permettez-moi de vérifier vos coordonnées (KYC)</i> <br>
                    <i><strong>Nom</strong>: {{comptedormant_campaign.Contact.Nom}}</i> <br>
                    <i><strong>Post_Nom</strong>: {{comptedormant_campaign.Contact.Post_Nom}}</i> <br>
                    <i><strong>Prénom</strong>: {{comptedormant_campaign.Contact.Prenom}}</i> <br>
                    <i><strong>Adresse</strong>: N°{{comptedormant_campaign.Contact.Numero}}
                        {{comptedormant_campaign.Contact.Rue}}
                        {{comptedormant_campaign.Contact.Quartier}}
                        {{comptedormant_campaign.Contact.Commune}}</i> <br>
                    <i><strong>Ville</strong>: {{comptedormant_campaign.Contact.Ville}}</i> <br>
                    <i><strong>Province</strong>: {{comptedormant_campaign.Contact.Province}}</i> <br>
                    <i><strong>Téléphone</strong>: {{comptedormant_campaign.Contact.phonenumber}}</i> <br>
                    <i><strong>Email</strong>: {{comptedormant_campaign.Contact.Email}}</i> <br>
                    <i><strong>Remarque</strong>: {{comptedormant_campaign.Contact.Remarque}}</i> <br>
                </p>
                <p><strong>Questions 6</strong>: <br>
                    <i>AVEZ-VOUS DAUTRES QUESTIONS. Puis je vous proposer de rencontrer notre commercial en agence sur
                        nos autres
                        produits et
                        services. Quelles date et heure vous arrangent ?</i>
                    <br> R/ {{comptedormant_campaign.questions6}}
                    <br>
                    <i><strong>Commentaires</strong>:
                        <br> R/ {{comptedormant_campaign.CommentaireQ6}}
                    </i>
                </p>
                <p><strong>Statut</strong>: <br>
                    <i>
                        Nous vous remercions du temps accordé et n'hésitez pas à nous
                        contacter au besoin
                    </i>
                    <br> R/ {{comptedormant_campaign.Statut}}
                </p>

                <p><strong>Trafic</strong>:
                    <br>
                    R/ {{comptedormant_campaign.Bound}}
                </p>

                <p><strong>Campaign name</strong>:
                    <br>
                    R/ {{comptedormant_campaign.campaignname}}
                </p>


                <p><strong>Remplie par l'agent</strong>: {{comptedormant_campaign.user}}</p>
                <!-- <p><strong>Bound</strong>: {{acquisition.Bound}}</p> -->

            </div>
        </div>
    </div>
</div>



{% endblock param_url %}

templates/pages/param_url/param_dat.html
{% extends 'base_params.html' %}
{% load static %}

{% block title %} DAT {% endblock title %}


{% block param_url %}

<div class="container my-5">
    <div class="card">
        <div class="card-header">
            <h6>CAMPAIGN <strong>{{dat_campaign.campaignname |upper}}</strong></h6>
            <div class="row">
                <h2>APPEL DE <strong>{{dat_campaign.Contact.phonenumber}}</strong></h2>
                <div class="d-flex justify-content-end">
                    <a href="{% url 'dat:dat_update' dat_campaign.id %}" role="button" class="btn btn-primary mr-2" style="color: aliceblue;font-weight: 700;">
                        MODIFIER
                    </a>
                    <a class="btn btn-info" href="{% url 'dat:export_dat_pdf' dat_campaign.id %}" target="_blank">
                        PDF
                    </a>
                </div>
            </div>  
        </div>
        
        <div class="card-body">
            <div class='details'>
                <p><strong>Questions 1</strong>: <br>
                    <i>Nous souhaiterions parler avec Mr/Mme X </i>
                    <br>
                    R/ {{dat_campaign.questions1}}
                </p>
                <p><strong>Questions 2</strong>: <br>
                    <i>Nous constatons que vous n'avez pas encore renouvelé votre dat_campaign alors que nous avons une campagne de
                        promotion en cours.
                        Puis-je suggérer de fixer un rendez-vous avec notre commercial pour reconduire votre dat_campaign ?</i>
                    <br>
                    R/ {{dat_campaign.questions2}}
                </p>
                <p><strong>Questions 3</strong>: <br>
                    <i>Permettez-moi de vérifier vos coordonnées (KYC)</i> <br>
                    <i><strong>Nom</strong>: {{dat_campaign.Contact.Nom}}</i> <br>
                    <i><strong>Post_Nom</strong>: {{dat_campaign.Contact.Post_Nom}}</i> <br>
                    <i><strong>Prénom</strong>: {{dat_campaign.Contact.Prenom}}</i> <br>
                    <i><strong>Adresse</strong>: N°{{dat_campaign.Contact.Numero}} {{dat_campaign.Contact.Rue}}
                        {{dat_campaign.Contact.Quartier}}
                        {{dat_campaign.Contact.Commune}}</i> <br>
                    <i><strong>Ville</strong>: {{dat_campaign.Contact.Ville}}</i> <br>
                    <i><strong>Province</strong>: {{dat_campaign.Contact.Province}}</i> <br>
                    <i><strong>Téléphone</strong>: {{dat_campaign.Contact.phonenumber}}</i> <br>
                    <i><strong>Email</strong>: {{dat_campaign.Contact.Email}}</i> <br>
                    <i><strong>Remarque</strong>: {{dat_campaign.Contact.Remarque}}</i> <br>
                </p>
                <p><strong>Questions 4</strong>: <br>
                    <i>(GOODBYE): Nous vous remercions du temps accordé et n'hésitez pas à nous contacter au besoin</i>
                    <br>
                    R/ {{dat_campaign.Statut}}
                </p>
                <p><strong>Type de trafic</strong>:
                    <br>
                    R/ {{dat_campaign.Bound}}
                </p>
                <p><strong>Campaign name</strong>:
                    <br>
                    R/ {{dat_campaign.campaignname}}
                </p>
                <p><strong>Remplie par l'agent</strong>: {{dat_campaign.user}}</p>
            </div>
        </div>
    </div>  
</div>

{% endblock param_url %}

templates/pages/param_url/param_recouvrement.html
{% extends 'base_params.html' %}
{% load static %}

{% block title %} RECOUVREMENT {% endblock title %}


{% block param_url %}

<div class="container my-5">
    <div class="card">
        <div class="card-header">
            <h6>CAMPAIGN <strong>{{recouvrement_campaign.campaignname |upper}}</strong></h6>
            <div class="row">
                <h2>APPEL DE <strong>{{recouvrement_campaign.Contact.phonenumber}}</strong></h2>
                <div class="d-flex justify-content-end">
                    <a href="{% url 'recouvrement:recouvrement_update' recouvrement_campaign.id %}" role="button" class="btn btn-primary mr-2"
                        style="color: aliceblue;font-weight: 700;">
                        MODIFIER
                    </a>
                    <a class="btn btn-info" href="{% url 'recouvrement:export_recouvrement_pdf' recouvrement_campaign.id %}" target="_blank">
                        PDF
                    </a>
                </div>
            </div>
        </div>

        <div class="card-body">
            <div class='details'>
                <p><strong>Questions 1</strong>: <br>
                    <i>Bonjour, c'est {{user.profile.sexe|lower}} <strong>{{ user.first_name|capfirst}}</strong>
                    de Advans.
                    Nous souhaiterions parler avec Mr/Mme X </i>
                    <br>
                    R/ {{recouvrement_campaign.questions1}}
                </p>
                <p><strong>Questions 2</strong>: <br>
                    <i>
                        Nous constatons que vous n'avez pas encore honoré votre remboursement. Puis-je vous inviter à vous rendre dans le point
                        de vente le plus proche.
                    </i>
                    <br>
                    R/ {{recouvrement_campaign.questions2}}
                </p>
                <p><strong>KYC</strong>: <br>
                    <i>Permettez-moi de vérifier vos coordonnées (KYC)</i> <br>
                    <i><strong>Nom</strong>: {{recouvrement_campaign.Contact.Nom}}</i> <br>
                    <i><strong>Post_Nom</strong>: {{recouvrement_campaign.Contact.Post_Nom}}</i> <br>
                    <i><strong>Prénom</strong>: {{recouvrement_campaign.Contact.Prenom}}</i> <br>
                    <i><strong>Adresse</strong>: N°{{recouvrement_campaign.Contact.Numero}} {{recouvrement_campaign.Contact.Rue}}
                        {{recouvrement_campaign.Contact.Quartier}}
                        {{recouvrement_campaign.Contact.Commune}}</i> <br>
                    <i><strong>Ville</strong>: {{recouvrement_campaign.Contact.Ville}}</i> <br>
                    <i><strong>Province</strong>: {{recouvrement_campaign.Contact.Province}}</i> <br>
                    <i><strong>Téléphone</strong>: {{recouvrement_campaign.Contact.phonenumber}}</i> <br>
                    <i><strong>Email</strong>: {{recouvrement_campaign.Contact.Email}}</i> <br>
                    <i><strong>Remarque</strong>: {{recouvrement_campaign.Contact.Remarque}}</i> <br>
                </p>
                <p><strong>Questions 4</strong>: <br>
                    <i>(GOODBYE): Nous vous remercions du temps accordé et n'hésitez pas à nous contacter au besoin</i>
                    <br>
                    R/ {{recouvrement_campaign.Statut}}
                </p>
                <p><strong>Type de trafic</strong>:
                    <br>
                    R/ {{recouvrement_campaign.Bound}}
                </p>
                <p><strong>Campaign name</strong>:
                    <br>
                    R/ {{recouvrement_campaign.campaignname}}
                </p>
                <p><strong>Remplie par l'agent</strong>: {{recouvrement_campaign.user}}</p>
            </div>
        </div>
    </div>
</div>



{% endblock param_url %}